server:
  port: 8782

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: order-management 
  zipkin:
    base-url: http://106.12.192.115:9411/ 
  sleuth:
    sampler:
      probability: 1 
feign:
  hystrix:
    enabled: true
  client:
    config:
      default:
        connectTimeout: 2000
        readTimeout: 2000
env: test
